spring:
  application:
    name: spring-cloud-eureka1
server:
  port: 8001
eureka:
  instance:
    hostname: eureka-service1
  client:
    serviceUrl:
      defaultZone: http://eureka-service2:8002/eureka/,http://eureka-service3:8003/eureka/
    register-with-eureka: false
    fetch-registry: false

