spring:
  application:
    name: spring-cloud-eureka3
server:
  port: 8003
eureka:
  instance:
    hostname: eureka-service3
  client:
    serviceUrl:
      defaultZone: http://eureka-service1:8001/eureka/,http://eureka-service2:8002/eureka/
    register-with-eureka: false
    fetch-registry: false
