spring:
  application:
    name: spring-cloud-eureka2
server:
  port: 8002
eureka:
  instance:
    hostname: eureka-service2
  client:
    serviceUrl:
      defaultZone: http://eureka-service1:8001/eureka/,http://eureka-service3:8003/eureka/
    register-with-eureka: false
    fetch-registry: false

